version: '3.7'

services:
  app_email:
    container_name: webmail
    build: .
    restart: always
    volumes: 
      - .:/app_email
      # - .:/app_email/node_modules
    depends_on: 
      - db
    links: 
      - db
    ports: 
      - 3000:3000
    command: npm start

  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - dbdata-volume:/data/db
    # environment: 
    #   MONGO_INITDB_USERNAME: 
    #   MONGO_INITDB_PASSWORD:
    #   MONGO_INITDB_DATABASE:

volumes: 
  dbdata-volume:
